### ISSUE TITLE
BS-1 Создать классы моделей БД

### ISSUE THREAD

**Issue by DraKoN7719** [DraKoN7719/battleship#2]
Создать следующие классы моделей БД:

> Пользователь :
> id - long
> логин - string
> пароль - string (хеш-свёртка)

> Бот :
> id - long
> сложность - int

> Сохранённая игра :
> id игры - UUID
> название игры - string
> id пользователя - long
> id бота- long
> поле пользователя - string
> поле бота - string
> текущий ход - long

> История игр :
> id игры - UUID
> id пользователя 1 - long
> id пользователя 2/бота - long
> результат игры(id победителя) - long

**Comment by PSergey42** [comment]
Сделано

**Comment by DraKoN7719** [comment]
Также добавить расстановку пользователя

> Расстановка: 
> Название - string
> id пользователя - long
> расстановка - string
